### ISSUE TITLE
Please update the nginx.conf when we release the new docker image

### ISSUE THREAD

**Issue by tmatsuo** [a1comms/cf-gae-flex-php#1]
The change is available at:
https://github.com/GoogleCloudPlatform/php-docker/pull/270/files

We'll notify here once we release it. Sorry for the BC break.

**Comment by tmatsuo** [comment]
Released: https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-05-04-10-45

**Comment by iamacarpet** [comment]
@tmatsuo No problem, thanks for letting me know!

**Comment by tmatsuo** [comment]
Hi, sorry for another BC break, but another change is happening at:
https://github.com/GoogleCloudPlatform/php-docker/pull/285

**Comment by tmatsuo** [comment]
Let us know if you feel too much BC breaks, so that we can hold off the change and bundle it with another BC break for the `http` level user-supplied nginx config.

**Comment by iamacarpet** [comment]
Hello @tmatsuo 
Don't worry about it, this repo is defunct anyway as support aren't able to provide a config that'll work to parse the X-Forwarded-For properly anyway, saying we should just wait for the REMOTE_ADDR bug to be fixed then see where it leaves us. Thanks for the update though!

EDIT: I should clarify, this config does parse it, but the trusted IP list isn't something that can be reliably provided according to support, so it's as good as useless using this method.
